"""Added timezone to refresh_tokens table

Revision ID: 911195f918d9
Revises: 3b9cb9bc6eba
Create Date: 2026-03-29 17:32:36.832106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '911195f918d9'
down_revision: Union[str, Sequence[str], None] = '3b9cb9bc6eba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
