"""Unique category name per user

Revision ID: f73428e5ae4e
Revises: a7f8bc9b30b0
Create Date: 2026-02-01 22:39:22.724665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f73428e5ae4e'
down_revision: Union[str, Sequence[str], None] = 'a7f8bc9b30b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint('uq_user_category_name', 'categories', ['user_id', 'name'])
    # ### end Alembic commands ###
    # noinspection PyTypeChecker
    with op.batch_alter_table("categories") as batch_op:
        batch_op.create_unique_constraint(
            "uq_user_category_name",
            ["user_id", "name"]
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('uq_user_category_name', 'categories', type_='unique')
    # ### end Alembic commands ###
    # noinspection PyTypeChecker
    with op.batch_alter_table("categories") as batch_op:
        batch_op.drop_constraint(
            "uq_user_category_name",
            type_="unique"
        )
